In [1]:
import torch

In [2]:
# Gradient will be automatically calculate
x = torch.rand(5,requires_grad=True)
print(x)
y = x+4
print(y)
z = x*y
print(z)
z = z.mean()
print(z)

tensor([0.3612, 0.9278, 0.9859, 0.0194, 0.0573], requires_grad=True)
tensor([4.3612, 4.9278, 4.9859, 4.0194, 4.0573], grad_fn=<AddBackward0>)
tensor([1.5753, 4.5720, 4.9157, 0.0778, 0.2323], grad_fn=<MulBackward0>)
tensor(2.2746, grad_fn=<MeanBackward0>)


In [3]:
z.backward() # dz/dx
print(x.grad)

tensor([0.9445, 1.1711, 1.1944, 0.8077, 0.8229])


In [ ]:
# Prevent calculating gradients
'''
3 options:
x.requires_grad_(False)
x.detach()
with torch.no_grad():

'''

x = torch.rand(3,requires_grad=True)
y = torch.rand(4,requires_grad=True)
z = torch.rand(5,requires_grad=True)

# Using required_grad_()
print(x)
x.requires_grad_(False)
print(x)

# Using detach()   
d = x.detach() # Will create a new tensor with same value without gradients
print(d)


# Using torch.no_grad()
with torch.no_grad():
    s = x+x              
print(s)


tensor([0.2783, 0.7663, 0.7172], requires_grad=True)
tensor([0.2783, 0.7663, 0.7172])
tensor([0.2783, 0.7663, 0.7172])
tensor([0.5565, 1.5327, 1.4343])
