In [2]:
import torch

In [3]:
# Gradient will be automatically calculate
x = torch.rand(5,requires_grad=True)
print(x)
y = x+4
print(y)
z = x*y
print(z)
z = z.mean()
print(z)

tensor([0.3814, 0.0330, 0.3829, 0.3643, 0.3493], requires_grad=True)
tensor([4.3814, 4.0330, 4.3829, 4.3643, 4.3493], grad_fn=<AddBackward0>)
tensor([1.6711, 0.1331, 1.6780, 1.5897, 1.5192], grad_fn=<MulBackward0>)
tensor(1.3182, grad_fn=<MeanBackward0>)


In [4]:
z.backward() # dz/dx
print(x.grad)

tensor([0.9526, 0.8132, 0.9531, 0.9457, 0.9397])


In [5]:
# Prevent calculating gradients
'''
3 options:
x.requires_grad_(False)
x.detach()
with torch.no_grad():

'''

x = torch.rand(3,requires_grad=True)
y = torch.rand(4,requires_grad=True)
z = torch.rand(5,requires_grad=True)

# Using required_grad_()
print(x)
x.requires_grad_(False)
print(x)

# Using detach()   
d = x.detach() # Will create a new tensor with same value without gradients
print(d)


# Using torch.no_grad()
with torch.no_grad():
    s = x+x              
print(s)


tensor([0.7494, 0.0379, 0.7514], requires_grad=True)
tensor([0.7494, 0.0379, 0.7514])
tensor([0.7494, 0.0379, 0.7514])
tensor([1.4987, 0.0759, 1.5029])


In [13]:
x = torch.ones(4,requires_grad=True)
result = (2*x).sum()
result.backward()

In [14]:
# gradient
print(x.grad)
# Empty gradient
x.grad.zero_()


tensor([2., 2., 2., 2.])


tensor([0., 0., 0., 0.])