In [ ]:
'''
# Complete model
torch.save(model,path)

# load saved model
model = torch.load(path)
model.eval()
'''

# '''
# # save state dict
# torch.save(model.state_dict(),path)
# # model must be created again with parameters
# model = Model(**args,**kwargs)
# model.load_state_dict(torch.load(path))
# model.eval()
# '''



In [1]:
import torch
import torch.nn as nn

In [2]:
# Define model class
class Model(nn.Module):
    def __init__(self,n_input_features):
        super().__init__()
        self.linear = nn.Linear(n_input_features,1)
        
    def forward(self,x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred
    
    
model = Model(n_input_features=6)
# Then train the model....


# Save whole model
file_name = 'Models/model.pth'
torch.save(model,file_name)



In [4]:
# Load the model
model = torch.load(file_name)
model.eval()

for params in model.parameters():
    print(params)

Parameter containing:
tensor([[-0.1240,  0.1608,  0.2646,  0.1386,  0.2200, -0.1091]],
       requires_grad=True)
Parameter containing:
tensor([0.2547], requires_grad=True)


C:\Users\tahsi\AppData\Local\Temp\ipykernel_5744\3727752447.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(file_name)


In [5]:
# Save state dict
file_name = 'Models/model2.pth'
torch.save(model.state_dict(),file_name)

In [6]:
# Create model again 
model = Model(n_input_features=6)
model.load_state_dict(torch.load(file_name))
model.eval()


for params in model.parameters():
    print(params)

Parameter containing:
tensor([[-0.1240,  0.1608,  0.2646,  0.1386,  0.2200, -0.1091]],
       requires_grad=True)
Parameter containing:
tensor([0.2547], requires_grad=True)


C:\Users\tahsi\AppData\Local\Temp\ipykernel_5744\2133773946.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(file_name))
