In [43]:
import torch
import numpy as np

In [3]:
# 1D vector with 3 elements
x = torch.empty(3)
x

tensor([-2.0491e+03,  1.5372e-42,  0.0000e+00])

In [4]:
# 2D vector with 3 elements
y = torch.empty(2,3)
print(y)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# # 3D vector with 3 elements
z = torch.empty(3,3)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# tensor with random values
a = torch.rand(2,2)
a

tensor([[0.8386, 0.0620],
        [0.8316, 0.6104]])

In [7]:
# tensor with one value
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [8]:
# Check data type
print(b.dtype)  # By default data type is float
b = torch.ones(2,2,dtype=int) # Can define datatype
print(b.dtype)

torch.float32
torch.int64


In [9]:
# Check size of a tensor
print(b.size())

torch.Size([2, 2])


In [10]:
# Create a tensor with values
x = torch.Tensor([2.3,4.5])
x

tensor([2.3000, 4.5000])

In [11]:
# Add two tensors
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add(x)


tensor([[0.9205, 1.4941],
        [0.6159, 0.7321]])

In [ ]:
# Subtraction
z = x-y
z

tensor([[-0.1385, -0.1253],
        [-0.0450, -0.2987]])

In [13]:
# Multiplication
z = x*y
z

tensor([[0.2070, 0.5542],
        [0.0943, 0.1117]])

In [ ]:
# Division
z = x/y
z

tensor([[0.7385, 0.8452],
        [0.8639, 0.4205]])

In [23]:
# Slicing
x = torch.rand(6,4)
print(x)
print(x[:,0]) # All rows and 0 columns
print(x[0,:]) # All columns 0th row

tensor([[0.8021, 0.6831, 0.8613, 0.0080],
        [0.1858, 0.3381, 0.4132, 0.4857],
        [0.9969, 0.0248, 0.1501, 0.6615],
        [0.3528, 0.1585, 0.6313, 0.9818],
        [0.8064, 0.7144, 0.5411, 0.8856],
        [0.5900, 0.1639, 0.5345, 0.9804]])
tensor([0.8021, 0.1858, 0.9969, 0.3528, 0.8064, 0.5900])
tensor([0.8021, 0.6831, 0.8613, 0.0080])


In [27]:
z = x[1,1]
print(z)
# To get actual value call item method when we have 1 row 1 column tensor
print(z.item())

tensor(0.3381)
0.33814454078674316


In [ ]:
# Resizing a tensor calling view() method
x = torch.rand(6,6)

y = x.view(-1,6) # Row size will be automatically detected and column size is 6
print(y)

# Size of a tensor
print(y.size())

tensor([[0.4159, 0.6640, 0.1909, 0.2912, 0.2112, 0.1578],
        [0.4988, 0.7442, 0.8954, 0.1543, 0.1656, 0.4673],
        [0.7983, 0.6548, 0.9998, 0.2961, 0.9830, 0.3642],
        [0.2421, 0.1790, 0.8244, 0.1294, 0.6396, 0.5991],
        [0.9506, 0.4504, 0.0440, 0.9390, 0.8951, 0.0013],
        [0.9603, 0.7684, 0.1747, 0.4922, 0.7260, 0.7773]])
torch.Size([6, 6])


In [ ]:
a = torch.ones(5)
b = a.numpy() # Convert tensor into numpy
print(type(a))
print(type(b))


# If tensor is in cpu(not gpu) they will share same memory address
print('Before')
print(a)
print(b)
print('\nAfter') 
a.add_(1) # Both a and b will be changed as the share same memory location
print(a)
print(b)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
Before
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]

After
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [56]:
a = np.ones(5)
b = torch.from_numpy(a) # Convert numpy into tensor
print(type(b))

<class 'torch.Tensor'>


In [60]:
# Check cuda is available or not
if torch.cuda.is_available():
    device = torch.device('cuda')
    print('CUDA is Available')
    x = torch.ones(5,5,device=device)
    print(x)
    y = torch.ones(2,2).to(device)
    print(y)
else:
    
     print('CUDA is not Available')

CUDA is Available
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')


In [61]:
# calculate gradient of a tensor
x = torch.ones(4,4,requires_grad=True)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)